import { byId } from "@goblin-systems/goblin-design-system";

export function createAppDom(root: Document = document) {
  return {
    nav: byId<HTMLElement>("app-nav", root),
    navTriggerLabel: byId<HTMLElement>("nav-trigger-label", root),
    syncPhaseBadge: byId<HTMLElement>("sync-phase-badge", root),
    windowSubtitle: byId<HTMLElement>("window-subtitle", root),
    homeScreen: byId<HTMLElement>("screen-home", root),
    credentialsScreen: byId<HTMLElement>("screen-credentials", root),
    activityScreen: byId<HTMLElement>("screen-activity", root),
    settingsScreen: byId<HTMLElement>("screen-settings", root),
    credentialsCountBadge: byId<HTMLElement>("credentials-count-badge", root),
    credentialsListStatus: byId<HTMLElement>("credentials-list-status", root),
    credentialsEmptyState: byId<HTMLElement>("credentials-empty-state", root),
    credentialsList: byId<HTMLUListElement>("credentials-list", root),
    credentialsSupportBadge: byId<HTMLElement>("credentials-support-badge", root),
    credentialsSupportText: byId<HTMLElement>("credentials-support-text", root),
    credentialNameInput: byId<HTMLInputElement>("credential-name-input", root),
    credentialAccessKeyInput: byId<HTMLInputElement>("credential-access-key-input", root),
    credentialSecretKeyInput: byId<HTMLInputElement>("credential-secret-key-input", root),
    createCredentialBtn: byId<HTMLButtonElement>("create-credential-btn", root),
    credentialsResult: byId<HTMLElement>("credentials-result", root),
    remotePollingInput: byId<HTMLInputElement>("remote-polling-input", root),
    pollIntervalInput: byId<HTMLInputElement>("poll-interval-input", root),
    conflictStrategySelect: byId<HTMLSelectElement>("conflict-strategy-select", root),
    deleteSafetyInput: byId<HTMLInputElement>("delete-safety-input", root),
    activityDebugModeInput: byId<HTMLInputElement>("activity-debug-mode-input", root),
    debugLogStatusBadge: byId<HTMLElement>("debug-log-status-badge", root),
    debugLogStatusText: byId<HTMLElement>("debug-log-status-text", root),
    debugLogFilePath: byId<HTMLElement>("debug-log-file-path", root),
    openDebugLogFolderBtn: byId<HTMLButtonElement>("open-debug-log-folder-btn", root),
    saveSettingsBtn: byId<HTMLButtonElement>("save-settings-btn", root),
    settingsResult: byId<HTMLElement>("settings-result", root),
    statusPhaseInline: byId<HTMLElement>("status-phase-inline", root),
    statusSummary: byId<HTMLElement>("status-summary", root),
    statusOverviewLocal: byId<HTMLElement>("status-overview-local", root),
    statusOverviewRemote: byId<HTMLElement>("status-overview-remote", root),
    statusOverviewInSync: byId<HTMLElement>("status-overview-in-sync", root),
    statusOverviewNotInSync: byId<HTMLElement>("status-overview-not-in-sync", root),
    activityEmptyState: byId<HTMLElement>("activity-empty-state", root),
    activityList: byId<HTMLUListElement>("activity-list", root),

    // Home screen
    activeLocationSelect: byId<HTMLSelectElement>("active-location-select", root),
    fileTreeEmptyState: byId<HTMLElement>("file-tree-empty-state", root),
    fileTree: byId<HTMLUListElement>("file-tree", root),

    // Sync locations dialog
    locationsScreen: byId<HTMLElement>("screen-locations", root),
    locationsCountBadge: byId<HTMLElement>("locations-count-badge", root),
    locationsListStatus: byId<HTMLElement>("locations-list-status", root),
    locationsEmptyState: byId<HTMLElement>("locations-empty-state", root),
    locationsList: byId<HTMLUListElement>("locations-list", root),
    locationFormTitle: byId<HTMLElement>("location-form-title", root),
    locationLabelInput: byId<HTMLInputElement>("location-label-input", root),
    locationLocalFolderInput: byId<HTMLInputElement>("location-local-folder-input", root),
    locationRegionSelect: byId<HTMLSelectElement>("location-region-select", root),
    locationBucketInput: byId<HTMLInputElement>("location-bucket-input", root),
    locationCredentialSelect: byId<HTMLSelectElement>("location-credential-select", root),
    locationEnabledInput: byId<HTMLInputElement>("location-enabled-input", root),
    locationPollingInput: byId<HTMLInputElement>("location-polling-input", root),
    locationPollIntervalInput: byId<HTMLInputElement>("location-poll-interval-input", root),
    locationConflictStrategySelect: byId<HTMLSelectElement>("location-conflict-strategy-select", root),
    locationDeleteSafetyInput: byId<HTMLInputElement>("location-delete-safety-input", root),
    locationEditingId: byId<HTMLInputElement>("location-editing-id", root),
    saveLocationBtn: byId<HTMLButtonElement>("save-location-btn", root),
    cancelEditLocationBtn: byId<HTMLButtonElement>("cancel-edit-location-btn", root),
    locationBrowseFolderBtn: byId<HTMLButtonElement>("location-browse-folder-btn", root),
    locationsResult: byId<HTMLElement>("locations-result", root),
  };
}

export type AppDom = ReturnType<typeof createAppDom>;
