import { byId } from "@goblin-systems/goblin-design-system";

export function createAppDom(root: Document = document) {
  return {
    nav: byId<HTMLElement>("app-nav", root),
    syncPhaseBadge: byId<HTMLElement>("sync-phase-badge", root),
    windowSubtitle: byId<HTMLElement>("window-subtitle", root),
    homeScreen: byId<HTMLElement>("screen-home", root),
    credentialsScreen: byId<HTMLElement>("screen-credentials", root),
    activityScreen: byId<HTMLElement>("screen-activity", root),
    pollingScreen: byId<HTMLElement>("screen-polling", root),
    debugScreen: byId<HTMLElement>("screen-debug", root),
    conflictScreen: byId<HTMLElement>("screen-conflict", root),
    aboutScreen: byId<HTMLElement>("screen-about", root),
    credentialsCountBadge: byId<HTMLElement>("credentials-count-badge", root),
    credentialsListStatus: byId<HTMLElement>("credentials-list-status", root),
    credentialsEmptyState: byId<HTMLElement>("credentials-empty-state", root),
    credentialsList: byId<HTMLUListElement>("credentials-list", root),
    credentialsSupportBadge: byId<HTMLElement>("credentials-support-badge", root),
    credentialsSupportText: byId<HTMLElement>("credentials-support-text", root),
    credentialNameInput: byId<HTMLInputElement>("credential-name-input", root),
    credentialAccessKeyInput: byId<HTMLInputElement>("credential-access-key-input", root),
    credentialSecretKeyInput: byId<HTMLInputElement>("credential-secret-key-input", root),
    createCredentialBtn: byId<HTMLButtonElement>("create-credential-btn", root),
    credentialsResult: byId<HTMLElement>("credentials-result", root),
    remotePollingInput: byId<HTMLInputElement>("remote-polling-input", root),
    pollIntervalInput: byId<HTMLInputElement>("poll-interval-input", root),
    conflictStrategySelect: byId<HTMLSelectElement>("conflict-strategy-select", root),
    activityDebugModeInput: byId<HTMLInputElement>("activity-debug-mode-input", root),
    debugLogStatusBadge: byId<HTMLElement>("debug-log-status-badge", root),
    debugLogStatusText: byId<HTMLElement>("debug-log-status-text", root),
    debugLogFilePath: byId<HTMLElement>("debug-log-file-path", root),
    openDebugLogFolderBtn: byId<HTMLButtonElement>("open-debug-log-folder-btn", root),
    savePollingBtn: byId<HTMLButtonElement>("save-polling-btn", root),
    saveDebugBtn: byId<HTMLButtonElement>("save-debug-btn", root),
    saveConflictBtn: byId<HTMLButtonElement>("save-conflict-btn", root),
    pollingResult: byId<HTMLElement>("polling-result", root),
    debugResult: byId<HTMLElement>("debug-result", root),
    conflictResult: byId<HTMLElement>("conflict-result", root),
    statusPhaseInline: byId<HTMLElement>("status-phase-inline", root),
    statusSummary: byId<HTMLElement>("status-summary", root),
    statusOverviewLocalLabel: byId<HTMLElement>("status-overview-local-label", root),
    statusOverviewLocal: byId<HTMLElement>("status-overview-local", root),
    statusOverviewRemoteLabel: byId<HTMLElement>("status-overview-remote-label", root),
    statusOverviewRemote: byId<HTMLElement>("status-overview-remote", root),
    statusOverviewInSyncLabel: byId<HTMLElement>("status-overview-in-sync-label", root),
    statusOverviewInSync: byId<HTMLElement>("status-overview-in-sync", root),
    statusOverviewNotInSyncLabel: byId<HTMLElement>("status-overview-not-in-sync-label", root),
    statusOverviewNotInSync: byId<HTMLElement>("status-overview-not-in-sync", root),
    activityEmptyState: byId<HTMLElement>("activity-empty-state", root),
    activityList: byId<HTMLUListElement>("activity-list", root),

    // Home screen
    activeLocationSelect: byId<HTMLSelectElement>("active-location-select", root),
    fileTreeSection: byId<HTMLElement>("file-tree-section", root),
    binToolbar: byId<HTMLElement>("bin-toolbar", root),
    binSelectionSummary: byId<HTMLElement>("bin-selection-summary", root),
    restoreSelectedBtn: byId<HTMLButtonElement>("restore-selected-btn", root),
    purgeSelectedBtn: byId<HTMLButtonElement>("purge-selected-btn", root),
    fileTreeLoadingIndicator: byId<HTMLElement>("file-tree-loading-indicator", root),
    fileTreeEmptyState: byId<HTMLElement>("file-tree-empty-state", root),
    fileTree: byId<HTMLUListElement>("file-tree", root),

    // Sync locations dialog
    locationsScreen: byId<HTMLElement>("screen-locations", root),
    locationsCountBadge: byId<HTMLElement>("locations-count-badge", root),
    locationsListStatus: byId<HTMLElement>("locations-list-status", root),
    locationsEmptyState: byId<HTMLElement>("locations-empty-state", root),
    locationsList: byId<HTMLUListElement>("locations-list", root),
    locationFormTitle: byId<HTMLElement>("location-form-title", root),
    locationLabelInput: byId<HTMLInputElement>("location-label-input", root),
    locationLocalFolderInput: byId<HTMLInputElement>("location-local-folder-input", root),
    locationRegionSelect: byId<HTMLSelectElement>("location-region-select", root),
    locationBucketInput: byId<HTMLInputElement>("location-bucket-input", root),
    locationCredentialSelect: byId<HTMLSelectElement>("location-credential-select", root),
    locationObjectVersioningEnabledInput: byId<HTMLInputElement>("location-object-versioning-enabled-input", root),
    locationVersioningCheckboxWrap: byId<HTMLElement>("location-versioning-checkbox-wrap", root),
    locationVersioningCheckbox: byId<HTMLInputElement>("location-versioning-checkbox", root),
    locationVersioningBtnWrap: byId<HTMLElement>("location-versioning-btn-wrap", root),
    locationObjectVersioningBtn: byId<HTMLButtonElement>("location-object-versioning-btn", root),
    locationVersioningBtnSpinner: byId<HTMLElement>("location-versioning-btn-spinner", root),
    locationVersioningBtnIcon: byId<HTMLElement>("location-versioning-btn-icon", root),
    locationVersioningBtnLabel: byId<HTMLElement>("location-versioning-btn-label", root),
    locationEnabledInput: byId<HTMLInputElement>("location-enabled-input", root),
    locationPollingInput: byId<HTMLInputElement>("location-polling-input", root),
    locationPollIntervalInput: byId<HTMLInputElement>("location-poll-interval-input", root),
    locationConflictStrategySelect: byId<HTMLSelectElement>("location-conflict-strategy-select", root),
    locationRemoteBinEnabledInput: byId<HTMLInputElement>("location-remote-bin-enabled-input", root),
    locationRemoteBinRetentionInput: byId<HTMLInputElement>("location-remote-bin-retention-input", root),
    locationRemoteBinHint: byId<HTMLElement>("location-remote-bin-hint", root),
    locationEditingId: byId<HTMLInputElement>("location-editing-id", root),
    saveLocationBtn: byId<HTMLButtonElement>("save-location-btn", root),
    cancelEditLocationBtn: byId<HTMLButtonElement>("cancel-edit-location-btn", root),
    locationBrowseFolderBtn: byId<HTMLButtonElement>("location-browse-folder-btn", root),
    locationsResult: byId<HTMLElement>("locations-result", root),

    // Version history drawer
    fileVersionsDrawer: byId<HTMLElement>("drawer-file-versions", root),
    fileVersionsDrawerClose: byId<HTMLButtonElement>("drawer-file-versions-close", root),
    fileVersionsDrawerPath: byId<HTMLElement>("drawer-file-versions-path", root),
    fileVersionsDrawerLoading: byId<HTMLElement>("drawer-file-versions-loading", root),
    fileVersionsDrawerEmpty: byId<HTMLElement>("drawer-file-versions-empty", root),
    fileVersionsDrawerList: byId<HTMLUListElement>("drawer-file-versions-list", root),
    fileVersionsDrawerCompareToolbar: byId<HTMLElement>("drawer-file-versions-compare-toolbar", root),
    fileVersionsDrawerCompareBtn: byId<HTMLButtonElement>("drawer-file-versions-compare-btn", root),
    fileVersionsDrawerComparePanel: byId<HTMLElement>("drawer-file-versions-compare-panel", root),
  };
}

export type AppDom = ReturnType<typeof createAppDom>;
